from bitmessagemain import start
from bitmessagemain import stop
from bitmessagemain import getCurrentAddress
from bitmessagemain import getMessage
from bitmessagemain import sendMessage
from bitmessagemain import getMessageStatusByAckdata
from bitmessagemain import clearMessage 
from bitmessagemain import setBlacklist
from bitmessagemain import setWhitelist
